spring:
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product
    username: "root"
    password: "pass1234"
flyway:
  url: jdbc:mysql://localhost:3306/product
  schemas: product
  user: "root"
  password: "pass1234"